In [2]:
import pandas as pd

In [46]:
df = pd.read_csv('data/application_train.csv')
bureau = pd.read_csv('data/bureau.csv')
bureau['id'] = range(len(bureau))
bureau = pd.get_dummies(bureau)
counts = df[['SK_ID_CURR']].merge(bureau, how='left', on='SK_ID_CURR').groupby('SK_ID_CURR').agg(
    {'id': 'count', 'CREDIT_ACTIVE_Active': 'sum', 'AMT_CREDIT_SUM': 'mean'})

In [47]:
counts

            CREDIT_ACTIVE_Active  AMT_CREDIT_SUM  id
SK_ID_CURR
100002                       2.0    1.081319e+05   8
100003                       1.0    2.543501e+05   4
100004                       0.0    9.451890e+04   2
100006                       NaN             NaN   0
100007                       0.0    1.462500e+05   1
100008                       1.0    1.561485e+05   3
100009                       4.0    2.667118e+05  18
100010                       1.0    4.950000e+05   2
100011                       0.0    1.088071e+05   4
100012                       NaN             NaN   0
100014                       2.0    3.412416e+05   8
100015                       0.0    1.023739e+05   4
100016                       4.0    6.785486e+04   7
100017                       0.0    1.432950e+05   6
100018                       NaN             NaN   0
100019                       2.0    3.600000e+05   2
100020                       2.0    4.987125e+04   4
100021                       NaN             NaN   0
100022                       2.0    5.287500e+05   2
100023                       4.0    1.265917e+05  13
100024                       NaN             NaN   0
100025                       1.0    2.452500e+06   1
100026                       2.0    1.875000e+06   3
100027                       1.0    2.084325e+05   3
100029                       1.0    1.857008e+06   4
100030                       2.0    1.072385e+05   6
100031                       3.0    5.672359e+05   7
100032                       1.0    3.177900e+05   4
100033                       1.0    6.750000e+05   1
100034                       NaN             NaN   0
...                          ...             ...  ..
456225                       6.0    4.126880e+05   9
456226                       2.0    2.250000e+05   2
456227                       2.0    1.993106e+05   4
456228                       NaN             NaN   0
456229                       1.0    2.587500e+05   1
456230                       4.0    1.163869e+05  12
456231                       3.0    4.733479e+05   7
456232                       2.0    4.005000e+05   2
456233                       1.0    2.826633e+05   1
456234                       3.0    1.393960e+05  10
456235                       1.0    4.930500e+05   3
456236                       4.0    6.389756e+05  13
456237                       0.0    9.814500e+04   1
456238                       2.0    1.849170e+05   6
456239                       5.0    5.693011e+05  11
456240                       1.0    6.619950e+04   2
456241                       2.0    2.430000e+05   5
456242                       1.0    1.980000e+05   1
456243                       2.0    2.553962e+05   7
456244                       4.0    3.264789e+05  23
456245                       NaN             NaN   0
456246                       1.0    1.275000e+05   3
456247                       3.0    4.714057e+05  11
456248                       NaN             NaN   0
456249                       2.0    2.841430e+05  13
456251                       NaN             NaN   0
456252                       NaN             NaN   0
456253                       2.0    9.900000e+05   4
456254                       0.0    4.500000e+04   1
456255                       5.0    3.456290e+05  11

[307511 rows x 3 columns]

In [45]:
bureau

,SK_ID_CURR,SK_ID_BUREAU,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,...,CREDIT_TYPE_Interbank credit,CREDIT_TYPE_Loan for business development,CREDIT_TYPE_Loan for purchase of shares (margin lending),CREDIT_TYPE_Loan for the purchase of equipment,CREDIT_TYPE_Loan for working capital replenishment,CREDIT_TYPE_Microloan,CREDIT_TYPE_Mobile operator loan,CREDIT_TYPE_Mortgage,CREDIT_TYPE_Real estate loan,CREDIT_TYPE_Unknown type of loan
0,215354,5714462,-497,0,-153.0,-153.0,NaN,0,91323.000,0.000,...,0,0,0,0,0,0,0,0,0,0
1,215354,5714463,-208,0,1075.0,NaN,NaN,0,225000.000,171342.000,...,0,0,0,0,0,0,0,0,0,0
2,215354,5714464,-203,0,528.0,NaN,NaN,0,464323.500,NaN,...,0,0,0,0,0,0,0,0,0,0
3,215354,5714465,-203,0,NaN,NaN,NaN,0,90000.000,NaN,...,0,0,0,0,0,0,0,0,0,0
4,215354,5714466,-629,0,1197.0,NaN,77674.500,0,2700000.000,NaN,...,0,0,0,0,0,0,0,0,0,0
5,215354,5714467,-273,0,27460.0,NaN,0.000,0,180000.000,71017.380,...,0,0,0,0,0,0,0,0,0,0
6,215354,5714468,-43,0,79.0,NaN,0.000,0,42103.800,42103.800,...,0,0,0,0,0,0,0,0,0,0
7,162297,5714469,-1896,0,-1684.0,-1710.0,14985.000,0,76878.450,0.000,...,0,0,0,0,0,0,0,0,0,0
8,162297,5714470,-1146,0,-811.0,-840.0,0.000,0,103007.700,0.000,...,0,0,0,0,0,0,0,0,0,0
9,162297,5714471,-1146,0,-484.0,NaN,0.000,0,4500.000,0.000,...,0,0,0,0,0,0,0,0,0,0
10,162297,5714472,-1146,0,-180.0,NaN,0.000,0,337500.000,0.000,...,0,0,0,0,0,0,0,0,0,0
11,162297,5714473,-2456,0,-629.0,-825.0,NaN,0,675000.000,0.000,...,0,0,0,0,0,0,0,0,0,0
12,162297,5714474,-277,0,5261.0,NaN,0.000,0,7033500.000,NaN,...,0,0,0,0,0,0,0,1,0,0
13,402440,5714475,-96,0,269.0,NaN,0.000,0,89910.000,76905.000,...,0,0,0,0,0,0,0,0,0,0
14,238881,5714482,-318,0,-187.0,-187.0,NaN,0,0.000,0.000,...,0,0,0,0,0,0,0,0,0,0
15,238881,5714484,-2911,0,-2607.0,-2604.0,NaN,0,48555.000,NaN,...,0,0,0,0,0,0,0,0,0,0
16,238881,5714485,-2148,0,-1595.0,-987.0,NaN,0,135000.000,NaN,...,0,0,0,0,0,0,0,0,0,0
17,238881,5714486,-381,0,NaN,NaN,NaN,0,450000.000,520920.000,...,0,0,0,0,0,0,0,0,0,0
18,238881,5714487,-95,0,1720.0,NaN,NaN,0,67500.000,8131.500,...,0,0,0,0,0,0,0,0,0,0
19,238881,5714488,-444,0,-77.0,-77.0,0.000,0,107184.060,0.000,...,0,0,0,0,0,0,0,0,0,0
20,238881,5714489,-392,0,NaN,NaN,0.000,0,252000.000,23679.000,...,0,0,0,0,0,0,0,0,0,0
21,222183,5714491,-784,0,1008.0,NaN,0.000,0,0.000,-411.615,...,0,0,0,0,0,0,0,0,0,0
22,222183,5714492,-774,0,625.0,NaN,NaN,0,127840.500,0.000,...,0,0,0,0,0,0,0,0,0,0
23,222183,5714493,-395,0,1431.0,NaN,NaN,0,1350000.000,1185493.500,...,0,0,0,0,0,0,0,0,0,0
24,222183,5714495,-2744,0,-2561.0,-2559.0,310.500,0,18157.500,NaN,...,0,0,0,0,0,0,0,0,0,0
25,222183,5714496,-1103,0,-7.0,-343.0,20493.270,0,675000.000,0.000,...,0,0,0,0,0,0,0,0,0,0
26,222183,5714497,-315,0,1512.0,NaN,88821.000,0,3709552.500,NaN,...,0,0,0,0,0,0,0,0,0,0
27,426155,5714498,-1331,0,-994.0,-1023.0,1350.000,0,39433.500,0.000,...,0,0,0,0,0,0,0,0,0,0
28,426155,5714499,-2534,0,-2352.0,-2347.0,NaN,0,38830.500,0.000,...,0,0,0,0,0,0,0,0,0,0
29,426155,5714500,-845,0,-480.0,-480.0,0.000,0,67500.000,0.000,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1716398,312021,5057541,-1529,0,-829.0,-829.0,NaN,0,209898.000,0.000,...,0,0,0,0,0,0,0,0,0,0
1716399,232638,5057553,-613,0,721.0,NaN,NaN,0,972000.000,886297.500,...,0,0,0,0,0,0,0,0,0,0
1716400,318662,5057561,-815,0,1011.0,NaN,NaN,0,147150.000,105358.500,...,0,0,0,0,0,0,0,0,0,0
1716401,145715,5057569,-2333,0,-2027.0,-1984.0,173.070,0,35032.500,0.000,...,0,0,0,0,0,0,0,0,0,0
1716402,352358,5057580,-1714,0,-1530.0,-1564.0,NaN,0,35271.000,0.000,...,0,0,0,0,0,0,0,0,0,0
1716403,361928,5057589,-765,0,1061.0,NaN,NaN,0,1431000.000,1092226.500,...,0,0,0,0,0,0,0,0,0,0
1716404,166279,5057599,-99,0,997.0,NaN,0.000,0,450000.000,432787.500,...,0,0,0,0,0,0,0,0,0,0
1716405,438109,5057605,-2390,0,-2053.0,-2082.0,11317.590,0,112204.350,0.000,...,0,0,0,0,0,0,0,0,0,0
1716406,335468,5057618,-2517,0,-660.0,-2363.0,0.000,0,473940.000,0.000,...,0,0,0,0,0,0,0,0,0,0
1716407,146896,5057629,-1990,0,-1244.0,-1248.0,NaN,0,90000.000,NaN,...,0,0,0,0,0,0,0,0,0,0
1716408,146896,5057632,-434,0,-344.0,-344.0,NaN,0,234000.000,0.000,...,0,0,0,0,0,0,0,0,0,0
1716409,146896,5057636,-1705,0,-582.0,-582.0,0.000,0,0.000,0.000,...,0,0,0,0,0,0,0,0,0,0
1716410,280228,5057642,-575,0,813.0,NaN,NaN,0,67500.000,0.000,...,0,0,0,0,0,0,0,0,0,0
1716411,232118,5057652,-821,0,-425.0,-545.0,0.000,0,108765.720,0.000,...,0,0,0,0,0,0,0,0,0,0
1716412,288038,5057657,-541,0,7.0,NaN,NaN,0,225000.000,10971.000,...,0,0,0,0,0,0,0,0,0,0
1716413,288038,5057665,-463,0,-36.0,-36.0,6863.715,0,110878.470,0.000,...,0,0,0,0,0,0,0,0,0,0
1716414,445222,5057676,-1628,0,-1320.0,-1320.0,5693.625,0,57834.000,0.000,...,0,0,0,0,0,0,0,0,0,0
1716415,317217,5057684,-1970,0,-1577.0,-1577.0,NaN,0,93955.500,NaN,...,0,0,0,0,0,0,0,0,0,0
1716416,433007,5057695,-1100,0,-732.0,-731.0,NaN,0,98775.000,0.000,...,0,0,0,0,0,0,0,0,0,0
1716417,433007,5057703,-740,0,31128.0,NaN,NaN,0,67500.000,2466.000,...,0,0,0,0,0,0,0,0,0,0
1716418,433007,5057708,-1389,0,-1299.0,-1299.0,0.000,0,334158.435,0.000,...,0,0,0,0,0,0,0,0,0,0
1716419,352790,5057718,-1808,0,-1596.0,-1625.0,8100.000,0,28248.840,0.000,...,0,0,0,0,0,0,0,0,0,0
1716420,352790,5057725,-99,0,-83.0,-98.0,NaN,0,27000.000,0.000,...,0,0,0,0,0,0,0,0,0,0
1716421,375755,5057734,-1335,0,-1152.0,-1152.0,NaN,0,195408.000,0.000,...,0,0,0,0,0,0,0,0,0,0
1716422,375755,5057742,-2648,0,31129.0,-189.0,NaN,0,202500.000,0.000,...,0,0,0,0,0,0,0,0,0,0
1716423,259355,5057750,-44,0,-30.0,NaN,0.000,0,11250.000,11250.000,...,0,0,0,0,0,1,0,0,0,0
1716424,100044,5057754,-2648,0,-2433.0,-2493.0,5476.500,0,38130.840,0.000,...,0,0,0,0,0,0,0,0,0,0
1716425,100044,5057762,-1809,0,-1628.0,-970.0,NaN,0,15570.000,NaN,...,0,0,0,0,0,0,0,0,0,0
1716426,246829,5057770,-1878,0,-1513.0,-1513.0,NaN,0,36000.000,0.000,...,0,0,0,0,0,0,0,0,0,0
1716427,246829,5057778,-463,0,NaN,-387.0,NaN,0,22500.000,0.000,...,0,0,0,0,0,1,0,0,0,0

In [38]:
counts

            id
SK_ID_CURR
100002       8
100003       4
100004       2
100006       0
100007       1
100008       3
100009      18
100010       2
100011       4
100012       0
100014       8
100015       4
100016       7
100017       6
100018       0
100019       2
100020       4
100021       0
100022       2
100023      13
100024       0
100025       1
100026       3
100027       3
100029       4
100030       6
100031       7
100032       4
100033       1
100034       0
...         ..
456225       9
456226       2
456227       4
456228       0
456229       1
456230      12
456231       7
456232       2
456233       1
456234      10
456235       3
456236      13
456237       1
456238       6
456239      11
456240       2
456241       5
456242       1
456243       7
456244      23
456245       0
456246       3
456247      11
456248       0
456249      13
456251       0
456252       0
456253       4
456254       1
456255      11

[307511 rows x 1 columns]

In [31]:
df.head()

,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
SK_ID_CURR,,,,,,,,,,,,,,,,,,,,,
100002,8,8,8,8,8,8,8,8,8,8,...,8,8,8,8,8,8,8,8,8,8
100003,4,4,4,4,4,4,4,4,4,4,...,4,4,4,4,4,4,4,4,4,4
100004,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
100006,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,0,0,0,0,0,0
100007,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1

In [23]:
sorted(df['SK_ID_CURR'].unique())

[100002,
 100003,
 100004,
 100006,
 100007,
 100008,
 100009,
 100010,
 100011,
 100012,
 100014,
 100015,
 100016,
 100017,
 100018,
 100019,
 100020,
 100021,
 100022,
 100023,
 100024,
 100025,
 100026,
 100027,
 100029,
 100030,
 100031,
 100032,
 100033,
 100034,
 100035,
 100036,
 100037,
 100039,
 100040,
 100041,
 100043,
 100044,
 100045,
 100046,
 100047,
 100048,
 100049,
 100050,
 100051,
 100052,
 100053,
 100054,
 100055,
 100056,
 100058,
 100059,
 100060,
 100061,
 100062,
 100063,
 100064,
 100068,
 100069,
 100070,
 100071,
 100072,
 100073,
 100075,
 100076,
 100077,
 100078,
 100079,
 100080,
 100081,
 100082,
 100083,
 100084,
 100085,
 100086,
 100087,
 100088,
 100089,
 100093,
 100094,
 100095,
 100096,
 100097,
 100098,
 100099,
 100100,
 100101,
 100102,
 100103,
 100104,
 100105,
 100108,
 100110,
 100111,
 100112,
 100113,
 100114,
 100115,
 100116,
 100118,
 100119,
 100120,
 100121,
 100122,
 100123,
 100124,
 100125,
 100126,
 100127,
 100129,
 100130,
 100131,
 100132,
 100133,
 100134,
 100135,
 100136,
 100137,
 100138,
 100139,
 100140,
 100142,
 100143,
 100144,
 100145,
 100146,
 100147,
 100148,
 100149,
 100151,
 100152,
 100153,
 100154,
 100155,
 100156,
 100157,
 100158,
 100159,
 100160,
 100161,
 100162,
 100163,
 100164,
 100165,
 100166,
 100167,
 100173,
 100174,
 100175,
 100176,
 100177,
 100178,
 100179,
 100180,
 100181,
 100182,
 100183,
 100185,
 100186,
 100188,
 100189,
 100190,
 100191,
 100192,
 100193,
 100194,
 100195,
 100196,
 100197,
 100198,
 100199,
 100200,
 100201,
 100202,
 100203,
 100204,
 100205,
 100206,
 100207,
 100208,
 100209,
 100210,
 100211,
 100213,
 100214,
 100215,
 100216,
 100217,
 100218,
 100219,
 100220,
 100221,
 100224,
 100225,
 100226,
 100227,
 100228,
 100229,
 100230,
 100231,
 100233,
 100234,
 100235,
 100236,
 100237,
 100238,
 100239,
 100240,
 100242,
 100243,
 100244,
 100246,
 100247,
 100248,
 100249,
 100250,
 100251,
 100252,
 100254,
 100255,
 100257,
 100258,
 100259,
 100260,
 100261,
 100262,
 100263,
 100264,
 100265,
 100266,
 100267,
 100268,
 100269,
 100270,
 100272,
 100273,
 100274,
 100275,
 100276,
 100277,
 100279,
 100281,
 100282,
 100283,
 100284,
 100285,
 100286,
 100287,
 100288,
 100289,
 100290,
 100291,
 100292,
 100293,
 100294,
 100295,
 100296,
 100297,
 100298,
 100299,
 100300,
 100301,
 100302,
 100303,
 100304,
 100305,
 100307,
 100308,
 100309,
 100310,
 100313,
 100314,
 100315,
 100316,
 100317,
 100318,
 100319,
 100320,
 100321,
 100322,
 100323,
 100324,
 100325,
 100326,
 100327,
 100328,
 100329,
 100332,
 100333,
 100334,
 100335,
 100336,
 100337,
 100338,
 100339,
 100340,
 100341,
 100342,
 100343,
 100344,
 100345,
 100346,
 100347,
 100348,
 100349,
 100350,
 100351,
 100353,
 100354,
 100355,
 100356,
 100357,
 100359,
 100360,
 100361,
 100362,
 100363,
 100364,
 100365,
 100366,
 100368,
 100369,
 100370,
 100371,
 100372,
 100373,
 100374,
 100375,
 100376,
 100377,
 100378,
 100379,
 100380,
 100381,
 100383,
 100387,
 100388,
 100389,
 100390,
 100391,
 100392,
 100393,
 100394,
 100395,
 100396,
 100397,
 100398,
 100400,
 100401,
 100402,
 100403,
 100405,
 100406,
 100407,
 100408,
 100409,
 100410,
 100411,
 100412,
 100413,
 100414,
 100415,
 100417,
 100418,
 100419,
 100420,
 100421,
 100423,
 100424,
 100425,
 100427,
 100428,
 100429,
 100430,
 100431,
 100432,
 100433,
 100434,
 100435,
 100436,
 100437,
 100439,
 100440,
 100441,
 100442,
 100443,
 100448,
 100449,
 100451,
 100452,
 100453,
 100454,
 100455,
 100456,
 100457,
 100458,
 100459,
 100460,
 100461,
 100462,
 100463,
 100464,
 100465,
 100467,
 100468,
 100469,
 100470,
 100471,
 100472,
 100473,
 100474,
 100475,
 100476,
 100477,
 100478,
 100479,
 100480,
 100481,
 100482,
 100485,
 100486,
 100487,
 100488,
 100489,
 100490,
 100491,
 100492,
 100493,
 100495,
 100496,
 100497,
 100498,
 100499,
 100500,
 100501,
 100502,
 100503,
 100504,
 100505,
 100506,
 100507,
 100508,
 100509,
 100511,
 100513,
 100514,
 100515,
 100516,
 100518,
 100519,
 100520,
 100521,
 100522,
 100523,
 100524,
 100525,
 100526,
 100527,
 100528,
 100529,
 100530,
 100531,
 100532,
 100533,
 100534,
 100535,
 100536,
 100537,
 100538,
 100539,
 100540,
 100541,
 100542,
 100543,
 100544,
 100545,
 100546,
 100547,
 100549,
 100550,
 100554,
 100555,
 100556,
 100557,
 100558,
 100559,
 100560,
 100562,
 100563,
 100564,
 100565,
 100566,
 100567,
 100570,
 100571,
 100572,
 100573,
 100574,
 100575,
 100576,
 100577,
 100578,
 100579,
 100580,
 100581,
 100582,
 100583,
 100584,
 100585,
 100586,
 100587,
 100588,
 100589,
 100590,
 100593,
 100594,
 100595,
 100596,
 100597,
 100598,
 100599,
 100600,
 100601,
 100603,
 100604,
 100605,
 100606,
 100608,
 100609,
 100610,
 100611,
 100612,
 100614,
 100615,
 100616,
 100619,
 100620,
 100621,
 100623,
 100624,
 100626,
 100627,
 100628,
 100629,
 100630,
 100631,
 100632,
 100633,
 100634,
 100635,
 100636,
 100637,
 100638,
 100639,
 100640,
 100641,
 100642,
 100643,
 100644,
 100645,
 100646,
 100647,
 100648,
 100649,
 100650,
 100651,
 100652,
 100653,
 100654,
 100655,
 100656,
 100657,
 100658,
 100659,
 100660,
 100661,
 100662,
 100663,
 100664,
 100665,
 100666,
 100667,
 100668,
 100669,
 100670,
 100671,
 100672,
 100673,
 100674,
 100675,
 100676,
 100678,
 100679,
 100680,
 100681,
 100682,
 100683,
 100684,
 100685,
 100686,
 100687,
 100688,
 100689,
 100690,
 100691,
 100692,
 100693,
 100694,
 100695,
 100696,
 100697,
 100698,
 100700,
 100701,
 100703,
 100704,
 100705,
 100706,
 100707,
 100708,
 100709,
 100710,
 100712,
 100713,
 100714,
 100715,
 100716,
 100717,
 100718,
 100719,
 100720,
 100721,
 100722,
 100723,
 100724,
 100725,
 100726,
 100727,
 100728,
 100730,
 100731,
 100732,
 100733,
 100734,
 100735,
 100736,
 100737,
 100738,
 100739,
 100741,
 100742,
 100743,
 100746,
 100748,
 100749,
 100750,
 100755,
 100756,
 100757,
 100758,
 100759,
 100761,
 100764,
 100766,
 100767,
 100768,
 100769,
 100771,
 100773,
 100774,
 100775,
 100776,
 100778,
 100779,
 100780,
 100781,
 100782,
 100783,
 100784,
 100785,
 100786,
 100787,
 100788,
 100789,
 100790,
 100793,
 100794,
 100795,
 100796,
 100798,
 100799,
 100800,
 100801,
 100802,
 100803,
 100804,
 100805,
 100806,
 100807,
 100808,
 100809,
 100810,
 100811,
 100812,
 100813,
 100814,
 100815,
 100816,
 100817,
 100818,
 100819,
 100820,
 100821,
 100822,
 100824,
 100825,
 100827,
 100828,
 100829,
 100831,
 100832,
 100833,
 100834,
 100835,
 100837,
 100838,
 100839,
 100840,
 100841,
 100842,
 100843,
 100844,
 100845,
 100846,
 100847,
 100848,
 100849,
 100850,
 100851,
 100852,
 100853,
 100854,
 100855,
 100856,
 100857,
 100858,
 100859,
 100860,
 100861,
 100862,
 100863,
 100864,
 100865,
 100866,
 100867,
 100868,
 100869,
 100870,
 100871,
 100873,
 100874,
 100875,
 100876,
 100877,
 100878,
 100879,
 100880,
 100881,
 100882,
 100883,
 100884,
 100885,
 100886,
 100887,
 100888,
 100889,
 100890,
 100891,
 100892,
 100893,
 100894,
 100895,
 100896,
 100897,
 100898,
 100899,
 100900,
 100901,
 100902,
 100903,
 100904,
 100905,
 100906,
 100907,
 100908,
 100909,
 100911,
 100912,
 100914,
 100915,
 100916,
 100917,
 100919,
 100920,
 100921,
 100922,
 100923,
 100924,
 100925,
 100926,
 100927,
 100928,
 100929,
 100930,
 100932,
 100933,
 100934,
 100935,
 100936,
 100937,
 100938,
 100939,
 100940,
 100941,
 100942,
 100943,
 100944,
 100945,
 100946,
 100947,
 100948,
 100949,
 100950,
 100951,
 100954,
 100955,
 100956,
 100957,
 100958,
 100959,
 100960,
 100961,
 100962,
 100963,
 100964,
 100966,
 100967,
 100968,
 100969,
 100971,
 100972,
 100973,
 100974,
 100975,
 100976,
 100977,
 100978,
 100979,
 100980,
 100981,
 100985,
 100986,
 100988,
 100989,
 100990,
 100991,
 100992,
 100993,
 100994,
 100995,
 100996,
 100999,
 101000,
 101001,
 101003,
 101004,
 101006,
 101007,
 101009,
 101010,
 101011,
 101012,
 101013,
 101014,
 101015,
 101016,
 101017,
 101018,
 101019,
 101022,
 101023,
 101027,
 101028,
 101029,
 101030,
 101032,
 101033,
 101034,
 101035,
 101036,
 101037,
 101038,
 101039,
 101040,
 101042,
 101043,
 101044,
 101045,
 101046,
 101047,
 101048,
 101049,
 101050,
 101052,
 101053,
 101054,
 101058,
 101059,
 101060,
 101061,
 101062,
 101063,
 101065,
 101066,
 101067,
 101068,
 101069,
 101070,
 101071,
 101072,
 101073,
 101074,
 101075,
 101076,
 101077,
 101078,
 101080,
 101081,
 101082,
 101083,
 101084,
 101085,
 101086,
 101088,
 101089,
 101091,
 101093,
 101094,
 101095,
 101096,
 101098,
 101100,
 101101,
 101102,
 101103,
 101104,
 101105,
 101106,
 101108,
 101109,
 101110,
 101111,
 101112,
 101113,
 101114,
 101115,
 101116,
 101117,
 101119,
 101120,
 101121,
 101122,
 101123,
 101124,
 101127,
 101129,
 101130,
 101131,
 101132,
 101133,
 101134,
 101135,
 101137,
 101138,
 101139,
 101141,
 101142,
 101143,
 101144,
 101145,
 101146,
 101147,
 101148,
 101150,
 101151,
 101152,
 101153,
 101154,
 101155,
 101156,
 ...]

In [24]:
sorted(bureau['SK_ID_CURR'].unique())

[100001,
 100002,
 100003,
 100004,
 100005,
 100007,
 100008,
 100009,
 100010,
 100011,
 100013,
 100014,
 100015,
 100016,
 100017,
 100019,
 100020,
 100022,
 100023,
 100025,
 100026,
 100027,
 100028,
 100029,
 100030,
 100031,
 100032,
 100033,
 100035,
 100036,
 100037,
 100039,
 100041,
 100042,
 100043,
 100044,
 100045,
 100046,
 100047,
 100048,
 100049,
 100050,
 100053,
 100054,
 100055,
 100057,
 100058,
 100059,
 100060,
 100061,
 100062,
 100063,
 100064,
 100065,
 100066,
 100067,
 100068,
 100069,
 100070,
 100071,
 100072,
 100073,
 100074,
 100075,
 100076,
 100077,
 100078,
 100079,
 100080,
 100082,
 100083,
 100084,
 100085,
 100086,
 100087,
 100088,
 100089,
 100090,
 100091,
 100092,
 100093,
 100094,
 100096,
 100097,
 100099,
 100100,
 100102,
 100103,
 100104,
 100105,
 100106,
 100107,
 100108,
 100109,
 100110,
 100111,
 100112,
 100113,
 100114,
 100115,
 100116,
 100117,
 100119,
 100120,
 100121,
 100122,
 100123,
 100124,
 100125,
 100126,
 100128,
 100129,
 100130,
 100131,
 100132,
 100134,
 100135,
 100136,
 100138,
 100139,
 100142,
 100143,
 100145,
 100146,
 100147,
 100148,
 100149,
 100150,
 100151,
 100152,
 100153,
 100154,
 100155,
 100156,
 100157,
 100158,
 100159,
 100160,
 100161,
 100162,
 100163,
 100164,
 100165,
 100166,
 100167,
 100168,
 100169,
 100170,
 100171,
 100172,
 100173,
 100174,
 100175,
 100176,
 100177,
 100178,
 100179,
 100180,
 100181,
 100182,
 100183,
 100184,
 100185,
 100186,
 100187,
 100188,
 100190,
 100191,
 100192,
 100193,
 100194,
 100195,
 100196,
 100198,
 100199,
 100200,
 100201,
 100202,
 100203,
 100204,
 100205,
 100207,
 100208,
 100209,
 100210,
 100211,
 100212,
 100213,
 100215,
 100216,
 100217,
 100218,
 100219,
 100220,
 100221,
 100222,
 100223,
 100224,
 100225,
 100227,
 100228,
 100229,
 100230,
 100231,
 100232,
 100233,
 100234,
 100235,
 100237,
 100238,
 100239,
 100240,
 100241,
 100242,
 100243,
 100244,
 100245,
 100246,
 100247,
 100248,
 100249,
 100250,
 100251,
 100252,
 100253,
 100254,
 100255,
 100256,
 100257,
 100259,
 100260,
 100261,
 100262,
 100263,
 100264,
 100265,
 100266,
 100267,
 100268,
 100269,
 100270,
 100271,
 100272,
 100274,
 100275,
 100276,
 100278,
 100279,
 100280,
 100281,
 100283,
 100284,
 100285,
 100286,
 100289,
 100290,
 100291,
 100292,
 100293,
 100294,
 100295,
 100298,
 100299,
 100300,
 100301,
 100302,
 100303,
 100304,
 100306,
 100307,
 100308,
 100309,
 100310,
 100311,
 100312,
 100313,
 100314,
 100315,
 100316,
 100317,
 100318,
 100319,
 100320,
 100321,
 100322,
 100325,
 100326,
 100327,
 100328,
 100329,
 100330,
 100332,
 100333,
 100334,
 100335,
 100336,
 100338,
 100339,
 100341,
 100342,
 100343,
 100344,
 100345,
 100346,
 100347,
 100348,
 100349,
 100350,
 100351,
 100352,
 100356,
 100357,
 100358,
 100359,
 100360,
 100361,
 100362,
 100363,
 100364,
 100365,
 100366,
 100367,
 100368,
 100369,
 100370,
 100371,
 100372,
 100373,
 100374,
 100375,
 100376,
 100378,
 100381,
 100382,
 100383,
 100384,
 100385,
 100386,
 100387,
 100388,
 100390,
 100391,
 100392,
 100393,
 100394,
 100395,
 100396,
 100397,
 100399,
 100400,
 100403,
 100404,
 100406,
 100407,
 100409,
 100411,
 100414,
 100415,
 100416,
 100417,
 100418,
 100419,
 100420,
 100421,
 100422,
 100423,
 100424,
 100425,
 100426,
 100427,
 100428,
 100429,
 100430,
 100431,
 100432,
 100433,
 100434,
 100435,
 100436,
 100437,
 100438,
 100439,
 100440,
 100441,
 100443,
 100444,
 100446,
 100447,
 100448,
 100449,
 100450,
 100451,
 100453,
 100454,
 100455,
 100456,
 100458,
 100459,
 100460,
 100461,
 100462,
 100463,
 100464,
 100466,
 100470,
 100472,
 100473,
 100475,
 100476,
 100477,
 100478,
 100479,
 100481,
 100482,
 100483,
 100484,
 100485,
 100486,
 100488,
 100489,
 100492,
 100493,
 100494,
 100495,
 100496,
 100497,
 100498,
 100500,
 100501,
 100502,
 100503,
 100504,
 100505,
 100507,
 100508,
 100509,
 100510,
 100511,
 100512,
 100514,
 100515,
 100516,
 100517,
 100519,
 100521,
 100522,
 100523,
 100525,
 100527,
 100528,
 100530,
 100531,
 100534,
 100535,
 100536,
 100537,
 100538,
 100539,
 100540,
 100541,
 100542,
 100543,
 100544,
 100545,
 100546,
 100547,
 100548,
 100549,
 100550,
 100551,
 100552,
 100553,
 100554,
 100555,
 100557,
 100558,
 100560,
 100561,
 100562,
 100563,
 100564,
 100566,
 100567,
 100568,
 100570,
 100571,
 100572,
 100573,
 100574,
 100575,
 100577,
 100578,
 100579,
 100580,
 100581,
 100582,
 100583,
 100584,
 100585,
 100586,
 100587,
 100588,
 100589,
 100592,
 100593,
 100594,
 100595,
 100596,
 100597,
 100598,
 100599,
 100600,
 100601,
 100603,
 100605,
 100606,
 100607,
 100608,
 100610,
 100612,
 100614,
 100615,
 100617,
 100618,
 100619,
 100620,
 100621,
 100622,
 100624,
 100626,
 100627,
 100628,
 100629,
 100630,
 100631,
 100633,
 100635,
 100636,
 100637,
 100638,
 100639,
 100640,
 100643,
 100644,
 100645,
 100646,
 100647,
 100648,
 100649,
 100650,
 100651,
 100652,
 100653,
 100654,
 100655,
 100656,
 100657,
 100658,
 100660,
 100662,
 100663,
 100664,
 100666,
 100667,
 100668,
 100669,
 100670,
 100671,
 100672,
 100673,
 100674,
 100675,
 100677,
 100678,
 100679,
 100680,
 100681,
 100682,
 100683,
 100684,
 100685,
 100686,
 100687,
 100688,
 100689,
 100691,
 100692,
 100693,
 100694,
 100695,
 100696,
 100697,
 100699,
 100700,
 100702,
 100703,
 100704,
 100706,
 100707,
 100709,
 100710,
 100711,
 100712,
 100713,
 100714,
 100715,
 100716,
 100717,
 100718,
 100719,
 100720,
 100722,
 100724,
 100725,
 100726,
 100727,
 100728,
 100729,
 100730,
 100731,
 100732,
 100733,
 100734,
 100735,
 100736,
 100737,
 100738,
 100739,
 100741,
 100742,
 100743,
 100745,
 100746,
 100747,
 100748,
 100749,
 100750,
 100751,
 100752,
 100753,
 100754,
 100757,
 100758,
 100759,
 100760,
 100761,
 100762,
 100763,
 100764,
 100765,
 100766,
 100768,
 100769,
 100770,
 100771,
 100772,
 100773,
 100774,
 100775,
 100776,
 100777,
 100778,
 100779,
 100780,
 100781,
 100782,
 100783,
 100785,
 100786,
 100787,
 100788,
 100789,
 100790,
 100791,
 100792,
 100793,
 100794,
 100795,
 100796,
 100797,
 100798,
 100799,
 100800,
 100802,
 100803,
 100804,
 100805,
 100806,
 100807,
 100808,
 100809,
 100810,
 100811,
 100812,
 100813,
 100814,
 100815,
 100816,
 100817,
 100818,
 100819,
 100820,
 100821,
 100822,
 100823,
 100824,
 100826,
 100827,
 100829,
 100830,
 100831,
 100832,
 100833,
 100834,
 100835,
 100836,
 100838,
 100839,
 100840,
 100841,
 100842,
 100843,
 100844,
 100845,
 100846,
 100847,
 100848,
 100849,
 100850,
 100851,
 100852,
 100853,
 100854,
 100855,
 100858,
 100859,
 100861,
 100862,
 100863,
 100865,
 100866,
 100867,
 100869,
 100871,
 100872,
 100874,
 100875,
 100878,
 100879,
 100880,
 100882,
 100883,
 100884,
 100885,
 100886,
 100887,
 100888,
 100889,
 100890,
 100891,
 100893,
 100894,
 100896,
 100897,
 100898,
 100899,
 100900,
 100902,
 100903,
 100904,
 100905,
 100906,
 100907,
 100908,
 100910,
 100911,
 100912,
 100913,
 100915,
 100916,
 100917,
 100918,
 100919,
 100920,
 100921,
 100922,
 100923,
 100924,
 100925,
 100926,
 100927,
 100928,
 100929,
 100930,
 100931,
 100932,
 100934,
 100935,
 100937,
 100938,
 100939,
 100940,
 100942,
 100943,
 100944,
 100945,
 100946,
 100947,
 100948,
 100950,
 100951,
 100952,
 100953,
 100954,
 100955,
 100956,
 100958,
 100959,
 100960,
 100961,
 100962,
 100963,
 100964,
 100965,
 100966,
 100967,
 100968,
 100969,
 100970,
 100972,
 100973,
 100974,
 100975,
 100977,
 100978,
 100979,
 100980,
 100981,
 100982,
 100983,
 100984,
 100985,
 100986,
 100987,
 100988,
 100989,
 100990,
 100991,
 100992,
 100993,
 100994,
 100995,
 100996,
 100997,
 100998,
 100999,
 101000,
 101001,
 101002,
 101003,
 101004,
 101006,
 101007,
 101009,
 101011,
 101012,
 101014,
 101017,
 101018,
 101019,
 101020,
 101021,
 101022,
 101024,
 101025,
 101026,
 101028,
 101029,
 101031,
 101032,
 101033,
 101034,
 101035,
 101037,
 101038,
 101039,
 101040,
 101041,
 101042,
 101043,
 101044,
 101045,
 101046,
 101047,
 101048,
 101049,
 101050,
 101051,
 101052,
 101053,
 101054,
 101055,
 101056,
 101057,
 101058,
 101059,
 101060,
 101061,
 101062,
 101063,
 101064,
 101065,
 101066,
 101067,
 101068,
 101069,
 101070,
 101071,
 101072,
 101073,
 101074,
 101075,
 101076,
 101078,
 101079,
 101081,
 101083,
 101084,
 101085,
 101086,
 101087,
 101088,
 101089,
 101090,
 101092,
 101093,
 101095,
 101096,
 101097,
 101098,
 101099,
 101100,
 101101,
 101102,
 101103,
 101104,
 101105,
 101106,
 101107,
 101108,
 101110,
 101111,
 101112,
 101113,
 101114,
 101115,
 101116,
 101117,
 101118,
 101120,
 101121,
 101122,
 101123,
 101125,
 101126,
 101127,
 101128,
 101129,
 101131,
 101133,
 101134,
 101135,
 101137,
 101138,
 101139,
 101140,
 101141,
 101142,
 101144,
 101145,
 101146,
 101147,
 101148,
 101150,
 101151,
 101152,
 101153,
 101154,
 101155,
 101156,
 101157,
 101158,
 101159,
 101162,
 101164,
 101166,
 101167,
 101168,
 101169,
 101170,
 ...]